notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: change
    on_failure: always

language: c

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode7.2

compiler:
  - gcc
  - clang

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ../
    - make

after_success:
    - cd ../Samples
    - make

