notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: change
    on_failure: always

git:
  depth: 3

language: c

os:
  - linux
  - osx
  
sudo: required
dist: trusty

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install cmocka; else sudo apt-get install libcmocka-dev; fi

compiler:
  - gcc
  - clang

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make

after_success:
    - cd ../Samples
    - make
    - cd ../tests
    - make
    - ./tests.out

