sudo: required

notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: change
    on_failure: always

language: c

compiler:
  - gcc
  - clang

arch:
    packages:
        - cmake

    script:
        - "echo $CC"
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ../
        - make
        - cd ../Samples
        - make

script:
    - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

