dist: trusty
sudo: false

notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: change
    on_failure: always

language: c

compiler:
  - gcc
  - clang

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ../
    - make

after_success:
    - cd ../Samples
    - make

