notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: change
    on_failure: always

language: c

os:
  - linux
  - osx
  
sudo: false

addons:
  apt:
    packages:
      - libcmocka-dev

install:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install cmocka; fi

compiler:
  - gcc
  - clang

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make

after_success:
    - cd ../Samples
    - make
    - cd ../tests
    - make
    - ./tests

