notifications:
  email:
    recipients: nierro92@gmail.com
    on_success: change
    on_failure: always

git:
  depth: 3

language: c

os:
  - linux
  - osx
  
sudo: required
dist: trusty

install:
  - if [ $TRAVIS_OS_NAME = linux ]; then wget http://fr.archive.ubuntu.com/ubuntu/pool/universe/c/cmocka/libcmocka0_1.1.1-1_amd64.deb; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then wget http://fr.archive.ubuntu.com/ubuntu/pool/universe/c/cmocka/libcmocka-dev_1.1.1-1_amd64.deb; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo dpkg -i libcmocka0_1.1.1-1_amd64.deb libcmocka-dev_1.1.1-1_amd64.deb; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install valgrind; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew update; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install cmocka; fi

compiler:
  - gcc
  - clang

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_SAMPLES=true ../
    - make
    - ctest -V
