site_name: Libmodule Documentation
site_description: C simple and elegant implementation of an Actor library
site_author: Federico Di Pierro
repo_url: https://github.com/FedeDP/libmodule/

nav:
    - Home: index.md
    - Concepts:
        - concepts/concepts.md
        - Build: concepts/build.md
        - Module: concepts/mod.md
        - Context: concepts/ctx.md
    - Core API:
        - core/core.md
        - Module API: core/mod.md
        - Context API: core/ctx.md
    - Data Structures API:
        - structs/structs.md
        - Map: structs/map.md
        - List: structs/list.md
        - Queue: structs/queue.md
        - Stack: structs/stack.md
        - Bst: structs/bst.md
    - Reference counted memory: mem/mem.md
    - Thread Pool API: thpool/thpool.md

theme: readthedocs

markdown_extensions:
    - toc:
        permalink: "#"
    - def_list

plugins:
    - search
