image: archlinux
packages:
  - cmocka
  - valgrind
  - cmake
  - liburing-git
  - libkqueue
  - fuse3
sources:
  - https://github.com/FedeDP/libmodule
tasks:
  - prepare: |
      cd libmodule
      mkdir build_kqueue build_uring build_epoll build_fs
      (cd build_kqueue && cmake -DBUILD_TESTS=true -DBUILD_SAMPLES=true -DWITH_LIBKQUEUE=true -DBUILD_OOT_TEST=true -DWITH_VALGRIND=false ..)
      (cd build_uring && cmake -DBUILD_TESTS=true -DBUILD_SAMPLES=true -DWITH_LIBURING=true -DBUILD_OOT_TEST=true -DWITH_VALGRIND=false ..)
      (cd build_epoll && cmake -DBUILD_TESTS=true -DBUILD_SAMPLES=true -DBUILD_OOT_TEST=true ..)
      (cd build_fs && cmake -DBUILD_TESTS=true -DBUILD_SAMPLES=true -DWITH_FS=true -DBUILD_OOT_TEST=true ..)
  - build: |
      cd libmodule
      (cd build_kqueue && make)
      (cd build_uring && make)
      (cd build_epoll && make)
      (cd build_fs && make)
  - test: |
      cd libmodule
      (cd build_kqueue && ctest -V)
      (cd build_uring && ctest -V)
      (cd build_epoll && ctest -V)
      (cd build_fs && ctest -V)
  - install: |
      cd libmodule
      (cd build_kqueue && sudo make install)
      (cd build_uring && sudo make install)
      (cd build_epoll && sudo make install)
      (cd build_fs && sudo make install)
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
