image: fedora/latest
packages:
  - libcmocka-devel
  - valgrind
  - cmake
  - gcc-c++
  - rpm-build
  - fuse3-devel
sources:
  - https://github.com/FedeDP/libmodule
tasks:
  - prepare: |
      cd libmodule
      mkdir build
      cd build
      cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=true -DBUILD_SAMPLES=true ../
  - build: |
      cd libmodule/build
      make
  - test: |
      cd libmodule/build
      ctest -V
  - build_pkg: |
      cd libmodule/build
      cpack -G RPM
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
