image: freebsd/latest
packages:
  - cmocka
  - valgrind
  - cmake
  - fusefs-libs3
  - pkgconf
  - wget
sources:
  - https://github.com/FedeDP/libmodule
tasks:
  - prepare: |
      cd libmodule
      mkdir build build_fs
      (cd build && cmake -DBUILD_TESTS=true -DBUILD_SAMPLES=true -DBUILD_OOT_TEST=true ../)
      (cd build_fs && cmake -DBUILD_TESTS=true -DBUILD_SAMPLES=true -DWITH_FS=true -DBUILD_OOT_TEST=true ..)
  - build: |
      cd libmodule
      (cd build && make)
      (cd build_fs && make)
  - test: |
      cd libmodule
      (cd build && ctest -V)
      (cd build_fs && sudo kldload fusefs && ctest -V) #-> This requires fuse module to be loaded
  - install: |
      cd libmodule
      (cd build && sudo make install) 
      (cd build_fs && sudo make install) 
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
