image: freebsd/latest
packages:
  - cmocka
  #- valgrind
  - cmake
  - fusefs-libs3
  - pkgconf
sources:
  - https://github.com/FedeDP/libmodule
tasks:
  - prepare: |
      cd libmodule
      mkdir build build_fs
      (cd build && cmake -DBUILD_TESTS=true -DBUILD_SAMPLES=true ../)
      (cd build_fs && cmake -DBUILD_TESTS=true -DBUILD_SAMPLES=true -DWITH_FS=true ..)
  - build: |
      cd libmodule
      (cd build && make)
      (cd build_fs && make)
  - test: |
      cd libmodule
      (cd build && ctest -V)
      (cd build_fs && ctest -V)
triggers:
  - action: email
    condition: failure
    to: "<nierro92@gmail.com>"
