name: CI Build
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-ubuntu-amd64:
    name: build-ubuntu-amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMocka
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libcmocka-dev valgrind dpkg rpm libfuse3-dev fuse3 libkqueue-dev liburing-dev
      - name: Build and test no FS
        run: |
          mkdir build && cd build
          cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=On ..
          make package
          ctest -V
          cmake -DBUILD_OOT_TEST=On ..
          sudo make install
      - name: Build and test FS
        run: |
          mkdir build_fs && cd build_fs
          cmake -DBUILD_TESTS=On -DBUILD_SAMPLES=On -DWITH_FS=On ..
          make package
          ctest -V
          cmake -DBUILD_OOT_TEST=On ..
          sudo make install
      - name: Build and test kqueue
        run: |
          mkdir build_kqueue && cd build_kqueue
          cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=On -DWITH_LIBKQUEUE=true -DWITH_VALGRIND=false ..
          make package
          ctest -V
          cmake -DBUILD_OOT_TEST=On ..
          sudo make install
      - name: Build and test uring
        run: |
          mkdir build_uring && cd build_uring
          cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=On -DWITH_LIBURING=true -DWITH_VALGRIND=false ..
          make package
          ctest -V
          cmake -DBUILD_OOT_TEST=On ..
          sudo make install
          
  build-freebsd-amd64:
    runs-on: macos-12
    name: build-freebsd-amd64
    steps:
    - uses: actions/checkout@v3
      with:
        path: libmodule

    - name: Build and test
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: true
        sync: sshfs
        prepare: |
          pkg install -y cmake cmocka pkgconf valgrind fusefs-libs3
            
        run: |
          cd libmodule/
          mkdir build && cd build
          cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=On -DBUILD_OOT_TEST=true ..
          make
          ctest -V
          make install
          cd ..
          mkdir build_fs && cd build_fs
          cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=On -DBUILD_OOT_TEST=true -DWITH_FS=true ..
          make
          kldload fusefs
          ctest -V
          make install
          
  build-osx-amd64:
    name: build-osx-amd64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMocka
        run: |
          brew update
          brew install cmocka
      - name: Build and test
        run: |
          mkdir -p build
          cd build && cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=On ..
          cmake --build .
          ctest -V
          ls /usr/include
          sudo ln -s /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/* /usr/include/
          cmake -DBUILD_OOT_TEST=On ..
          sudo make install

  build-win-amd64:
    name: build-win-amd64
    runs-on: windows-latest
    env:
      PKG_CONFIG_PATH: "C:/Program Files (x86)/libkqueue/lib/pkgconfig/" # libkqueue installs its pc script here
    steps:
      - uses: actions/checkout@v3
        with:
          path: libmodule
      - uses: actions/checkout@v3
        with:
          repository: mheily/libkqueue
          path: libkqueue
          fetch-depth: 0
      - name: Build and Install libkqueue
        run: |
          cd libkqueue
          cmake -S . -B build_x64
          cmake --build build_x64 --target install --config Release --parallel 1
      - name: Build and test
        run: |
          cd libmodule 
          mkdir -p build
          cd build && cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=Off -DBUILD_OOT_TEST=On ..
          cmake --build . --target install --config Release
