name: CI Build
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-osx-amd64:
    name: build-osx-amd64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install CMocka
        run: |
          brew update
          brew install cmocka
      - name: Build and test
        run: |
          mkdir -p build
          cd build && cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=On -DBUILD_OOT_TEST=On ..
          cmake --build .
  build-win-amd64:
    name: build-win-amd64
    runs-on: windows-latest
    env:
      PKG_CONFIG_PATH: "C:/Program Files (x86)/libkqueue/lib/pkgconfig/" # libkqueue installs its pc script here
    steps:
      - uses: actions/checkout@v3
        with:
          path: libmodule
      - uses: actions/checkout@v3
        with:
          repository: mheily/libkqueue
          path: libkqueue
          fetch-depth: 0
      - name: Build and Install libkqueue
        run: |
          cd libkqueue
          cmake -S . -B build_x64 -DSTATICLIB=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
          cmake --build build_x64 --target install --config Release --parallel 1
      - name: Build and test
        run: |
          cd libmodule 
          mkdir -p build
          cd build && cmake -DBUILD_SAMPLES=On -DBUILD_TESTS=Off -DBUILD_OOT_TEST=On ..
          cmake --build .
